name: ProjectMultiTool
version: 1.2.1
author: Zach
main: pmt.terramc.us.Main
api-version: 1.13

commands:
  playtime:
    description: Check your or another player's playtime
    usage: /playtime {player}
  repairme:
    description: Repairs your currently held item using any available repair coins.
    usage: /repairme
  repairme give:
    description: (Admins) spawn repair coins
    usage: /repairme give (amount)